version: '3.3'

networks:
  server-backend:
  client:

services:
  # Java Spring Server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meteo_data
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    command: ["java", "-jar", "app.jar"]
    networks:
      - server-backend
    restart: on-failure

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: meteo_data
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - server-backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Database Management Utility
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_PORT: 5432
      ADMINER_DEFAULT_USERNAME: root
      ADMINER_DEFAULT_PASSWORD: root
      ADMINER_DEFAULT_DATABASE: meteo_data
    networks:
      - server-backend

volumes:
  postgres-data:
