version: '3.8'

networks:
  server-backend:
  client:

services:
  # Java Spring Server
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "6000:6000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/meteo_data
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - database
    command: ["java", "-jar", "app.jar"]
    networks:
      - server-backend
    restart: on-failure

  # Database
  database:
    build:
      context: .
      dockerfile: Dockerfile-database
    ports:
      - "3306:3306"
    networks:
      - server-backend
    volumes:
      - database-data:/var/lib/mysql
    command: --init-file /db/init.sql

  # Database Management Utility
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_PORT: 3306
      ADMINER_DEFAULT_USERNAME: root
      ADMINER_DEFAULT_PASSWORD: root
      ADMINER_DEFAULT_DATABASE: meteo_data
    networks:
      - server-backend

volumes:
  database-data: